<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Sunglasses Overview Report</title>

    <!-- Bootstrap Core CSS -->
    <link href="css/bootstrap.min.css" rel="stylesheet">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
<style>
body {
    padding-top: 70px; /* Required padding for .navbar-fixed-top. Remove if using .navbar-static-top. Change if height of navigation changes. */
}

.portfolio-item {
    margin-bottom: 25px;
}

footer {
    margin: 50px 0;
}

.navbar .navbar-brand {
    color: white;
}

.capture-name {
margin-top: 5px;
}
</style>
</head>

<body>

    <!-- Navigation -->
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#">Sunglasses</a>
                <p class="navbar-text">Overview Report</p>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>

    <!-- Page Content -->
    <div class="container">

        <!-- Page Heading -->
        <div class="row">
            <div class="col-lg-12">
                <h3 class="page-header">Comparison Results</h3>
            </div>
        </div>
        <!-- /.row -->
<#list data as dataEntry>
        <!-- entry -->
        <div class="row">
            <div class="col-md-3">
			    <a href="#" class="thumbnail">
			      <img src="file://${resourceManager.getBaselineImage(dataEntry.result.captureName).getCanonicalPath()}" alt="${dataEntry.result.captureName} baseline">
			    </a>
			     <div class="caption">
	            	<h4>Baseline</h4>
	            </div>
            </div>
           <div class="col-md-3">
			    <a href="#" class="thumbnail">
			      <img src="file://${resourceManager.getCaptureImage(dataEntry.result.captureName).getCanonicalPath()}" alt="${dataEntry.result.captureName} capture">
			    </a>
			     <div class="caption">
	            	<h4>Capture</h4>
	            </div>
            </div>
           <div class="col-md-3">
			    <a href="#" class="thumbnail">
					<img src="file://${resourceManager.getDiffImage(dataEntry.result.captureName).getCanonicalPath()}" alt="${dataEntry.result.captureName} diff">
			    </a>
			     <div class="caption">
	            	<h4>Diff</h4>
	            </div>
            </div>
            <div class="col-md-3">
                <h3 class="capture-name">${dataEntry.result.captureName}</h3>
                <p>Missmatch: ${dataEntry.result.missmatch}%</p>
                <span class="label label-${dataEntry.isPass()?string("success","danger")}">${dataEntry.isPass()?string("No Regression","Regression Found")}</span>
                <p></p>
            </div>
        </div>
        <!-- /.row -->
        <hr>
</#list>
        <!-- Footer -->
        <footer>
            <div class="row">
                <div class="col-lg-12">
                    <p>Generated by Sunglasses (${.now})</p>
                </div>
            </div>
            <!-- /.row -->
        </footer>

    </div>
    <!-- /.container -->
</body>

</html>
